name: CI/CD
on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .github/workflows/CICD.yml
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: nginx/unit-1.22.0-go1.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/go/pkg/mod
          key: server-${{ hashFiles('go.sum') }}
          restore-keys: server-
      - name: Install mssing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download
      - name: Run tests
        run: go test -v ./... -ginkgo.v

  build:
    name: Build executable
    runs-on: ubuntu-latest
    container: nginx/unit-1.22.0-go1.15
    if: contains(github.ref, 'refs/tags')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/go/pkg/mod
          key: server-${{ hashFiles('go.sum') }}
          restore-keys: server-
      - name: Install mssing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download
      - name: Build executable
        run: go build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: ./server

  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    needs: [test, build]
    if: contains(github.ref, 'refs/tags')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: server
      - name: Deploy via SSH
        run: |
          eval `ssh-agent`
          mkdir ~/.ssh
          ssh-keyscan -H noahfriedman.ca >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          ssh ubuntu@noahfriedman.ca "sudo systemctl stop unit"
          scp server ubuntu@noahfriedman.ca:~/
          ssh ubuntu@noahfriedman.ca "sudo systemctl start unit"
